[tool.poetry]
name = "lionagi"
version = "0.3.0"
description = "Towards automated general intelligence."
authors = ["HaiyangLi <quantocean.li@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
lion-openai = "^0.1.5"
ipython = ">=8.0.0"
aiocache = ">=0.12.0"
python-dotenv = "^1.0.1"
lion-core = "^0.3.14"


[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^24.8.0"}
isort = "^5.13.2"
setuptools = "^75.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
