[tool.poetry]
name = "lionagi"
version = "0.3.0"
description = ""
authors = ["HaiyangLi <122793010+ohdearquant@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.3"
lion-core = "0.2.7"
lion-openai = "^0.1.1"
aiocache = "^0.12.2"
ipython = "^8.27.0"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
black = "^24.8.0"
flake8 = "^7.1.1"
isort = "^5.13.2"
pre-commit = "^3.8.0"
pytest-asyncio = "^0.24.0"
poetry-dynamic-versioning = "^1.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
