# KB Gatekeeper Configuration
# This file configures the orchestrator completion check behavior

# Event processing timeouts
timeouts:
  agent_response: 600 # 10 minutes - max time for agent to respond
  swarm_execution: 7200 # 2 hours - max time for swarm to complete
  event_staleness: 86400 # 24 hours - when to flag stale events
  github_api_timeout: 30 # 30 seconds - GitHub API request timeout

# System limits
limits:
  max_parallel_events: 20 # Maximum events to process in parallel
  max_concurrent_swarms: 5 # Maximum swarms running simultaneously
  batch_size: 100 # GitHub API pagination size
  retry_attempts: 3 # Max retries for failed API calls

# Critical stages requiring sequential processing
critical_stages:
  - "stage:decision.review" # Stakeholder approval required
  - "stage:implementation.approved" # Governance checkpoint
  - "stage:metrics.review" # ROI validation required

# Event classification rules
event_classification:
  # Events that can be processed in parallel
  parallelizable:
    - "stage:research.requested"
    - "stage:research.proposed"
    - "stage:research.active"
    - "stage:implementation.approved"
    - "stage:implementation.active"
    - "stage:metrics.collection"

  # Events requiring sequential processing
  sequential:
    - "stage:decision.ready"
    - "stage:decision.review"
    - "stage:metrics.review"

  # Events that automatically block
  blocking_conditions:
    - "status:blocked"
    - "status:needs-revision"
    - "status:needs-approval"
    - "priority:critical AND status:in-progress"

# GitHub integration settings
github:
  api_base_url: "https://api.github.com"
  user_agent: "KB-Gatekeeper/1.0"

  # Label patterns for event detection
  label_patterns:
    stage_prefix: "stage:"
    priority_prefix: "priority:"
    category_prefix: "category:"
    status_prefix: "status:"
    agent_prefix: "agent:"

  # Required labels for valid KB events
  required_labels:
    - "research-request"
    - "category:*"
    - "priority:*"

  # Agent signature patterns in comments
  agent_signatures:
    orchestrator: '\[ORCHESTRATOR-\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\]'
    agent_generic: '\[[A-Z_]+-\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\]'
    completion_markers:
      - "Phase Complete"
      - "HANDOFF"
      - "Execution complete"
      - "Success"

# Research ID validation
research_id:
  pattern: '\b([A-Z]{3}_\d{3})\b'
  categories:
    - "AIO" # AI/Orchestration
    - "MEM" # Memory/Persistence
    - "TLI" # Tools/Integration
    - "ARC" # Architecture
    - "DEV" # Developer Experience
    - "UXP" # User Experience

# Swarm execution patterns
swarm_patterns:
  "kb-intake-swarm":
    agents: ["research_intake_agent", "context_discovery_agent"]
    max_duration: 600 # 10 minutes
    parallel_execution: true

  "kb-research-swarm":
    agents: [
      "codebase_analyst_agent",
      "memory_management_agent",
      "context_discovery_agent",
    ]
    max_duration: 3600 # 1 hour
    parallel_execution: true

  "kb-decision-swarm":
    agents: ["decision_synthesis_agent", "critic_agent"]
    max_duration: 1800 # 30 minutes
    parallel_execution: false

  "kb-decision-review-swarm":
    agents: ["peer_review_agent", "critic_agent"]
    max_duration: 2400 # 40 minutes
    parallel_execution: false

# Quality gates and validation
quality_gates:
  # Pre-transition validation
  pre_transition:
    - "current_stage_matches_expected"
    - "required_artifacts_exist"
    - "no_conflicting_labels"
    - "agent_signature_valid"
    - "timestamp_within_range"

  # Post-transition validation
  post_transition:
    - "single_stage_label_only"
    - "status_consistent_with_stage"
    - "responsible_agent_updated"
    - "transition_logged"
    - "next_agent_notified"

# Emergency override settings
emergency_override:
  min_justification_length: 20
  audit_trail_required: true
  auto_expire_hours: 24
  notification_channels:
    - "github_issue_comment"
    - "monitoring_webhook"

# Monitoring and alerting
monitoring:
  health_check_interval: 60 # seconds
  stale_event_threshold: 1440 # 24 hours in minutes

  # Alert thresholds
  alerts:
    critical:
      no_events_processed_minutes: 15
      agent_failure_rate_percent: 20
      lock_contention_count: 5
      processing_queue_depth: 50

    warning:
      cycle_time_multiplier: 2.0
      sequential_fallback_triggered: true
      resource_usage_percent: 80
      quality_gate_failure_percent: 10

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # What to log
  log_events:
    - "event_scans"
    - "completion_checks"
    - "state_transitions"
    - "emergency_overrides"
    - "api_errors"
    - "timeout_events"
