name: Dependency Review

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Dependency Review
      uses: actions/dependency-review-action@v2

    - name: Send notifications for vulnerabilities
      if: failure()
      run: |
        echo "Vulnerabilities found. Sending notification..."
        # Add your notification logic here
