name: Secret Scan

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Secret Scan
      uses: actions/secret-scan-action@v1

    - name: Send notifications for secrets found
      if: failure()
      run: |
        echo "Secrets found. Sending notification..."
        # Add your notification logic here
